### ISSUE TITLE
Unhandled Error

### ISSUE THREAD

**Issue by StabbyCutyou** [crawshaw/littleboss#1]
Hello,

Was taking a look as I may have a need for something like this, and out of habit I ran megacheck against the repo.

You seem to have an error on line 522 that will end up getting ignored by the next call assign to that variable on 525.

I'm still reading the code and understanding the approach so, not sure if this represents a real issue or is just a false-positive but I thought I would pass it along.

Very cool stuff, all the same! Thanks for building this!

**Comment by crawshaw** [comment]
Thanks, you're right. I'll push a quick fix, but a real fix should have a test case, and this is a particularly hard case to test right now. As I flesh out the parent<->child pipe protocol it should be possible to test this.

**Comment by StabbyCutyou** [comment]
👍 Sounds good, thanks for the reply.
