### ISSUE TITLE
why listen unix socket?

### ISSUE THREAD

**Issue by iampastor** [crawshaw/littleboss#5]
hi:
    I was thinking write something like this before,  when I found you work, I think this is really what I want, and I read a little about the code, I am a little confused about the unix socket, I think without the unix socket listener, all the command flags can also be handled. So why listen on an unix socket to handle command?

**Comment by crawshaw** [comment]
The unix socket is used to communicate between a running littleboss and a new instance. When you type:

```
./mybin -littleboss=status
./mybin -littleboss=reload
```

Both of these processes find the unix socket and communicate with the running littleboss.

There are alternatives, but this seems like the simplest.
